---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argocd-deployment
  name: argocd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argocd-deployment
    spec:
      serviceAccountName: karthi-sa
      containers:
      - image: quay.io/vinothb/tekton-hello-world
        name: tekton-argocd
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
        - name: vinothb-pull-secret
