#Also a Stateless Application using deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  replicas: 6
  selector:
    matchLabels:
      app: temp-nginx
  template:
    metadata:
      labels:
        app: temp-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest#1.14.2 #1.16.1
        ports:
        - containerPort: 80
